### ISSUE TITLE
Windows specific issue: running "npx rdvue" yields  unexpected errors,  see image 

### ISSUE THREAD

**Issue by Saspect-IO** [realdecoy/rdvue#157]
Currently it works when I install rdvue globally "npm i -g rdvue" and run the command without **npx**  "rdvue create-project"

![image](https://user-images.githubusercontent.com/29488727/120547139-4f7d2d80-c3b6-11eb-9ac3-5b505748b798.png)

**Comment by andre-vidal** [comment]
The above issue was caused due to a bad deployment of the package. please see version [v2.1.0](https://github.com/realdecoy/rdvue/releases/tag/v2.1.0) for resolution
