### ISSUE TITLE
Generated page style tag should be "scoped"

### ISSUE THREAD

**Issue by carl-clarke** [realdecoy/rdvue#21]
- missing scoped attribute for generated page.
- remove the default css rules within the generated class. eg:

.test {
    display: grid;
    grid-column-gap: 1rem;
    grid-template-columns: 1fr auto auto 1fr;
    justify-items: center;
    align-items: center;
}

should just be:

.test {
  // Write your styles here.
}

**Comment by vidalCreates** [comment]
resolved in v0.5.7
